/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TennisMatchOrganizer;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sumit
 */
public class PlayerListFrame extends javax.swing.JFrame {

    private ArrayList<String> players;
    static boolean isAccepted = true;
    
    static boolean isViewed = false;
    
    TennisApp playersInfo;
    
    /**
     * Creates new form PlayerListFrame
     */
    public PlayerListFrame() {
        initComponents();
        players = new ArrayList<String>();
        playersInfo = new TennisApp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playerListLbl = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        display_Pane = new javax.swing.JTextPane();
        numOfMales_Lbl = new javax.swing.JLabel();
        numOfFemales_Lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        malesNum_Pane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        femalesNum_Pane = new javax.swing.JTextPane();
        Clear_btn = new javax.swing.JButton();
        goToMatchScheduler_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerListLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playerListLbl.setText("List of Players");

        UpdateBtn.setText("Update List");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(display_Pane);

        numOfMales_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numOfMales_Lbl.setText("Num. of males: ");

        numOfFemales_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numOfFemales_Lbl.setText("Num. of females: ");

        jScrollPane1.setViewportView(malesNum_Pane);

        jScrollPane3.setViewportView(femalesNum_Pane);

        Clear_btn.setText("Clear");
        Clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btnActionPerformed(evt);
            }
        });

        goToMatchScheduler_Btn.setText("Schedule Matches here");
        goToMatchScheduler_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToMatchScheduler_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(UpdateBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(playerListLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numOfMales_Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numOfFemales_Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Clear_btn)
                            .addComponent(goToMatchScheduler_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(playerListLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateBtn)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfMales_Lbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfFemales_Lbl)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(Clear_btn)
                        .addGap(24, 24, 24)
                        .addComponent(goToMatchScheduler_Btn)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        //display_Pane.removeAll();
        //display_Pane.repaint();
        
        try{
            
            File file = new File("GUI_PlayerList.txt");
            BufferedReader read = new BufferedReader(new FileReader(file));
            
            String aPlayer;
            while((aPlayer = read.readLine()) != null)
            {
                System.out.println(aPlayer);
                //players.add(read.readLine());
                players.add(aPlayer);
            }
            read.close();
            
        }catch(IOException e){
            System.out.println("File is not found");
        }
        
        String allPlayers = "";
        if (isAccepted) {
            for (String p : players) {
                allPlayers += p + "\n";
                display_Pane.setText(allPlayers);

            }
            isAccepted = false;
        }
        
        System.out.println(playersInfo.getNumOfMales());
        String numOfMales = Integer.toString(playersInfo.getNumOfMales());
        malesNum_Pane.setText(numOfMales);
        
        System.out.println(playersInfo.getNumOfFemales());
        String numOfFemales = Integer.toString(playersInfo.getNumOfFemales());
        femalesNum_Pane.setText(numOfFemales);
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void Clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btnActionPerformed
        // TODO add your handling code here:
        display_Pane.setText("");

        PrintWriter write;
        try {
            write = new PrintWriter("GUI_PlayerList.txt");
            write.println();
            write.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PlayerListFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Clear_btnActionPerformed

    private void goToMatchScheduler_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToMatchScheduler_BtnActionPerformed
        // TODO add your handling code here:
        if (!isViewed) {
            MatchScheduler matchSchedule = new MatchScheduler();
            matchSchedule.setVisible(true);
            matchSchedule.playerLbl_update();
            matchSchedule.comboBoxUpdate();
            isViewed = true;
        }
    }//GEN-LAST:event_goToMatchScheduler_BtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_btn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextPane display_Pane;
    private javax.swing.JTextPane femalesNum_Pane;
    private javax.swing.JButton goToMatchScheduler_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane malesNum_Pane;
    private javax.swing.JLabel numOfFemales_Lbl;
    private javax.swing.JLabel numOfMales_Lbl;
    private javax.swing.JLabel playerListLbl;
    // End of variables declaration//GEN-END:variables
}
